### ISSUE TITLE
Specify spatial extent with multiple geometries and/or placenames

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#106] opened 2023-07-11 03:04 UTC
**Creator Name:** John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)
 
Specify the geographic (spatial) context of a dataset in multiple ways:
1. Case 1: a simple bound-box or point geometry (Geographic long/lat in decimal degrees on WGS84 datum)
2. Case 2: complex “multi-polygon” geometries (including inner rings) representing disjoint patches of data 
3. Case 3: standardize only 1 way that geometry is to be encoded (e.g., GeoJSON)
4. Case 4: allow multiple placenames to specify geographic context, location or vicinity of a dataset (i.e., a vocabulary of place Concepts  grounded to an authoritative gazetteer, e.g., GNIS)
5. Case 5: allow multiple geometries and placenames to be specified on a single dataset.

## Problem Statement

The spatial extent of a dataset provides important context for finding relevant datasets and for discerning fitness for use but is often poorly/ ambiguously specified. The spatial extent of the data is also inconistently specified using various incorrect or non-standard representions of geometries. The spatial extent generally specifies the maximum spatial boundary of the data but may also need to identify interior disjoint spatial areas or gaps within the data to provide consumers/SMEs ability to determine more precisely if the actual spatial coverage of the data will meet their needs.

Geometries that represent more precisely the patch of ground the data is about is especially important for finding and determining the relevance of remotely sensed imagery (scenes) over large areas.

## Additional context, comments, or links - *Optional*

A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by fellahst** [comment] 2024-01-03 22:49
The requirement is addressed in the [Spatial Metadata guideline](https://doi-do.github.io/dcat-us/#spatial-metadata) section. Placenames are identified as URI of [dcterms:Location](https://doi-do.github.io/dcat-us/#properties-for-location). This class can have different geometries.

**Comment by TDabolt** [comment] 2024-01-05 18:45
I agree w/ Stefan interpretation.  I wonder if there was something deeper issue not articulated in the original comment that may indicate a lack of understanding of the Spatial Metadata Guideline or which requires edits to the guideline.  From the schema perspective the issue is addressed.  Recommend closing and flagging for monitoring implementation.

**Closed** 2024-01-25 21:01 UTC
Labels: Requirements Request, spatial, Final Review
