### ISSUE TITLE
Referenced diagram is missing

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#147] opened 2023-11-21 20:26 UTC
**Name:** Morgan Daniels

**Affiliation:** USAID, mdaniels@usaid.gov

**Type of issue:** Editorial, Administrative

Section # / Table #: [3 conformance](https://doi-do.github.io/dcat-us/#conformance-to-dcat-3)

**Issue:**

- **Administrative Comment**: Referenced diagram is missing

Original email submission: 
[USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx](https://github.com/DOI-DO/dcat-us/files/13430653/USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx)

**Comment by hkdctol** [comment] 2024-01-09 23:10
Will the diagram be created?

**Comment by fellahst** [comment] 2024-01-22 23:10
Yes, it will be created before the release. This ticket is closed as it is a duplicate of #184

**Closed by fellahst** 2024-01-22 23:10 UTC
Labels: documentation
