### ISSUE TITLE
Ensure that all available properties in DCAT-US v1.1 have clear mappings to properties in DCAT-US v3

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#145] opened 2023-11-21 20:13 UTC
**Name:** Mike Shallcross

**Affiliation:** ICPSR, shallcro@umich.edu

**Type of issue:** Schema, Editorial

Section # / Table #: None specified

**Issue:**

- **Substantive Comment**: DCAT-US v1.1 includes a 'bureauCode' property (https://resources.data.gov/resources/dcat-us/#bureauCode) and it is not clear how this would map to DCAT-US v3.

- **Rationale**: The absence of clear metadata mappings or crosswalks will make it more difficult for organizations to transform their metadata records and templates from DCAT-US v1.1 to DCAT-US v3.

- **Proposed Disposition:** Please ensure that all available properties in DCAT-US v1.1 have clear mappings to properties in DCAT-US v3. In cases where no mapping exists, please provide specific guidance as to how legacy metadata values (such as bureauCode) should be represented.

Original email submission: 
[ICPSR_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430487/ICPSR_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by hkdctol** [comment] 2024-01-09 23:11
If there are multiple issues that call for a mapping, create a task for that and close issues

**Comment by fellahst** [comment] 2024-01-25 19:19
Duplicate of #143

**Closed by fellahst** 2024-01-25 19:19 UTC
Labels: documentation
